"""empty message

Revision ID: dd989211c23b
Revises: 1d187db49574
Create Date: 2021-01-09 13:28:32.552348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd989211c23b'
down_revision = '1d187db49574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
